Add check to prefer explicit lists over ~w and ~W sigils
rrrene/credo pull request #1032
Opened 2023-03-15 15:44 UTC by adamu

This is a check I have wanted myself for a while. I thought I would submit it upstream in case it's useful to others.

I have added it as disabled by default/controversial.

2023-12-14 16:54 UTC, rrrene requested changes
Looking really good. Just some housekeeping items and a little feature request 😄👍

2023-12-14 16:54 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +      params: []
I think we need at least two params to be able to configure this check:

One to only apply this to atom lists, e.g. disallow `~w/atom1 atom2/a`.

One that makes it so we only trigger the check when `\` is used to include a "spaced element" in the list, e.g. `~w/file\ 1.docx file\ 2.docx/` would trigger, but `~w/strict --format json/` would not when this param is set to `true`.

2023-12-14 16:54 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +          [~S({"key":"value"}), ~S({"key2":"value2"})]
```suggestion
      # preferred

          ["foo", "bar", "baz"]
          [:"例（括弧）+追加", :別言葉]
          [~S({"key":"value"}), ~S({"key2":"value2"})]
          
      # NOT preferred

          ~w'foo bar baz'
          ~w/例（括弧）+追加 別言葉/a
          ~W({"key":"value"} {"key2":"value2"})

      Like all `Readability` issues, this one is not a technical concern.
      But you can improve the odds of others reading and liking your code by making
      it easier to follow.
```

This should be consistent with other Readability checks (lead with the preferred variant and include the readability disclaimer) :+1:

2023-12-14 16:54 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +      via the sigil.
```suggestion
      Code is read more times than it is written and although the ~w and ~W sigils 
      allow for brevity in code, explicit list definitions have the benefit that they are 
      both relatively brief and completely unambiguous.
```

I think that leading with the benefits of what NOT to do weakens the reasoning behind this check. Instead we should put the reading > writing argument first :+1:

2023-12-14 16:54 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +        trigger: :sigil_w,
The `:trigger` has to be the piece of code that triggered the issue (and should be highlighted in e.g. an editor). That would be `"~w"` here.

2023-12-14 16:54 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +        trigger: :sigil_W,
see above

2023-12-14 16:54 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +        message: ~S{Avoid ~w sigil: ~w(foo bar), prefer explicit lists: ["foo", "bar"]},
I am irritated by the fact that the messages for `~w` and `~W` are different. 

What was the reason for this decision?

2024-01-30 05:43 UTC, rrrene reviewed
Checking in: Any news?

2024-01-30 05:43 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +defmodule Credo.Check.Readability.NoListSigils do
Also, please rename to `ListSigils` :+1:

2024-01-30 05:43 UTC, rrrene commented on lib/credo/check/readability/no_list_sigils.ex
> +  """
```suggestion
```

Checks don't define module docs.

2024-03-05 05:42 UTC, rrrene commented
Checking in: Any update?

2024-03-05 05:51 UTC, adamu commented
Hi @rrrene apologies for the delay responding. This PR was open for 7 months before it got any comments, and during that time I solved my own needs locally with changes similar to the contents of this PR. Coming back to this isn't a high priority for me right now so please feel free to make any necessary changes directly, close, or accept an alternative implementation or PR!

2024-03-05 06:01 UTC, rrrene commented
Fair enough, sorry for not responding within your timeframe 👍

2024-03-05 06:01 UTC, closed without merging

2025-06-26 08:23 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +          [~S({"key":"value"}), ~S({"key2":"value2"})]
cd9c39f7

2025-06-26 08:23 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +      via the sigil.
cd9c39f7

2025-06-26 08:23 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +        trigger: :sigil_w,
a73d16fb

2025-06-26 08:24 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +        trigger: :sigil_W,
a73d16fb

2025-06-26 08:25 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +        message: ~S{Avoid ~w sigil: ~w(foo bar), prefer explicit lists: ["foo", "bar"]},
I'm not sure, it was probably related to the fact that `~W` does not interpolate. Anyway I unified the message in c8ba7512.

2025-06-26 08:25 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +defmodule Credo.Check.Readability.NoListSigils do
2613e94d

2025-06-26 08:25 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +  """
cd9c39f7

2025-06-26 08:27 UTC, adamu commented on lib/credo/check/readability/no_list_sigils.ex
> +      params: []
It's been a while since I looked at this, but does the `\` behaviour do anything. In iex it seems to have no effect:

```elixir
iex(1)> ~w(foo\ bar baz)
["foo", "bar", "baz"]
```

What is the reason why you think we should have an option to only apply the rule to atom lists?