feat: allow ignoring module attributes in Credo.Check.Readability.StrictModuleLayout
rrrene/credo pull request #1048
Opened 2023-06-12 20:41 UTC by btkostner

A lot of libraries define custom attributes and DSLs that adjust code in the next function. This PR allows users to ignore specific attributes from the `Credo.Check.Readability.StrictModuleLayout` check. Documentation and tests included.

Examples:
- `@decorate` [library](https://hexdocs.pm/decorator/readme.html)
- `@trace` [libraries](https://hexdocs.pm/new_relic_agent/NewRelic.Tracer.html#content)

2023-06-13 17:27 UTC, zorbash commented on lib/credo/check/readability/strict_module_layout.ex
> +        therefor appear anywhere in the module. Useful for custom DSLs that use attributes
[nit] therefore

2023-12-19 11:44 UTC, rrrene requested changes
I like this. Don't know if I could re-run the failed checks, but pushing a new commit with the requested changes should do it 👍

2023-12-19 11:44 UTC, rrrene commented on lib/credo/check/readability/strict_module_layout.ex
> +                false
Remove the comments please.

This should ave the added benefit that GitHub Actions will be triggered again :+1:

2023-12-19 18:08 UTC, btkostner commented
Alright, checks are running again 👍

2023-12-22 06:04 UTC, merged

2023-12-22 06:05 UTC, rrrene commented
@btkostner Thx! Will be released for X-Mas 🎄 👍

2023-12-22 17:22 UTC, btkostner commented
@rrrene Awesome! Thank you for your work maintaining this awesome library 🎊