Ignore PredicateFunctionNames when is impl
rrrene/credo pull request #1121
Opened 2024-03-24 09:34 UTC by quangngd

# Overview

- Closes #1108

# Impl details

If any `:def, :defp, :defmacro` is preceded with `:impl`, we ignore.

Code is mostly inspired from the impl of `Specs`

2024-03-25 18:50 UTC, rrrene commented
I like this in principle and will add suggestions later this week.

2024-03-26 04:48 UTC, rrrene commented on test/credo/check/readability/predicate_function_names_test.exs
> +
The proposed change yields a couple of false negatives which we should iron out before I review this PR:

```suggestion

  test "it should report a violation with false negatives" do
    """
    defmodule FooImpl do
      def impl(false), do: false
      def impl(true), do: true

      def is_bar do
      end
    end
    """
    |> to_source_file
    |> run_check(@described_check)
    |> assert_issue()
  end

  test "it should report a violation with false negatives /2" do
    """
    defmodule FooImpl do

      impl(true)

      def is_bar do
      end
    end
    """
    |> to_source_file
    |> run_check(@described_check)
    |> assert_issue()
  end

  test "it should report a violation with false negatives /3" do
    """
    defmodule Foo do
      @impl is_bar(a)
    end

    defmodule FooImpl do
      def is_bar do
      end
    end
    """
    |> to_source_file
    |> run_check(@described_check)
    |> assert_issue()
  end

  test "it should report a violation with false negatives /4" do
    """
    defmodule Foo do
      @impl true
    end

    defmodule FooImpl do
      def is_bar do
      end
    end
    """
    |> to_source_file
    |> run_check(@described_check)
    |> assert_issue()
  end
```

2024-03-27 03:21 UTC, quangngd commented on test/credo/check/readability/predicate_function_names_test.exs
> +
Sure! I took another look and came up with some changes.

2024-03-29 18:30 UTC, rrrene requested changes
Two more nitpicks, than we should be ready to merge  :+1:

2024-03-29 18:30 UTC, rrrene commented on lib/credo/check/readability/predicate_function_names.ex
> +    [:impl | acc]
Let's rename this atom to something more descriptive, like `:record_next_definition`, so that it tells what it does.

2024-03-29 18:30 UTC, rrrene commented on lib/credo/check/readability/predicate_function_names.ex
> +    Credo.Code.prewalk(source_file, &traverse(&1, &2, issue_meta, impl_list))
This traverses the whole file for `@impl` even if there is no need.

I would love for this logic to be reversed:

```elixir
issue_candidates = Credo.Code.prewalk(source_file, &traverse(&1, &2, issue_meta))

if issue_candidates == [] do
  []
else
  impl_list = Credo.Code.prewalk(source_file, &find_impls(&1, &2))

  # and then reject the issue_candidates that have an `@impl`
end
```

WDYT?

2024-03-30 15:03 UTC, quangngd commented on lib/credo/check/readability/predicate_function_names.ex
> +    [:impl | acc]
updated

2024-03-30 15:03 UTC, quangngd commented on lib/credo/check/readability/predicate_function_names.ex
> +    Credo.Code.prewalk(source_file, &traverse(&1, &2, issue_meta, impl_list))
refactored

2024-03-31 13:47 UTC, merged

2024-03-31 13:47 UTC, rrrene commented
@quangngd Thx! ✌️