Add check for specs containing structs to cut down on compile-time dependencies
rrrene/credo pull request #830
Opened 2020-12-02 02:55 UTC by andersonmcook

I was recently working on a project that would recompile ~70 files each time it was recompiled.  I did some digging and figured out that it was a result of using structs eg `%SomeStruct{}` in specs. Switching them out to `SomeStruct.t()` (and making that type) cut down on the modules that would be recompiled each time. Structs create compile-time dependencies and this will warn about structs being used in specs.

I'm happy to turn this off by default or tag it as experimental :)

Thanks for the wonderful library!

2020-12-07 16:45 UTC, rrrene requested changes
This seems like a really great addition for Credo.

A few requests:

2020-12-07 16:45 UTC, rrrene commented on test/credo/check/warning/spec_with_struct_test.exs
> +    defstruct [:id, name]
Shouldn't this be `:name`?

2020-12-07 16:45 UTC, rrrene commented on test/credo/check/warning/spec_with_struct_test.exs
> +  @a_struct_module """
Why do we need two structs for the tests?

2020-12-07 16:45 UTC, rrrene commented on lib/credo/check/warning/spec_with_struct.ex
> +          @spec a_function(MyModule.t()) :: any
Please use the style and wording found in the other checks:

https://github.com/rrrene/credo/blob/bd85e260d87bb177c1ee63cb61fba1561150347a/lib/credo/check/warning/raise_inside_rescue.ex#L9-L31

2020-12-07 16:45 UTC, rrrene commented on lib/credo/check/warning/spec_with_struct.ex
> +  defp traverse({:spec, meta, args}, issues, issue_meta) do
Doesn't this also get called for macros, functions and variables of the name "spec"?

2020-12-07 17:56 UTC, andersonmcook commented on test/credo/check/warning/spec_with_struct_test.exs
> +    defstruct [:id, name]
Thanks!  Fixed in https://github.com/rrrene/credo/pull/830/commits/32c6e19d212695cdf71e3fa57e46bc2d93430362

2020-12-07 17:58 UTC, andersonmcook commented on test/credo/check/warning/spec_with_struct_test.exs
> +  @a_struct_module """
I wanted to test that I could catch multiple issues for different structs and that I was formatting issues correctly.

2020-12-07 17:58 UTC, andersonmcook commented on lib/credo/check/warning/spec_with_struct.ex
> +          @spec a_function(MyModule.t()) :: any
Thanks! Fixed in https://github.com/rrrene/credo/pull/830/commits/32c6e19d212695cdf71e3fa57e46bc2d93430362

2020-12-07 17:59 UTC, andersonmcook commented on lib/credo/check/warning/spec_with_struct.ex
> +  defp traverse({:spec, meta, args}, issues, issue_meta) do
Great catch!  I made the check a little more specific by looking at `::` and `:when` to ignore functions/macros and variables named `spec` in https://github.com/rrrene/credo/pull/830/commits/32c6e19d212695cdf71e3fa57e46bc2d93430362

2020-12-12 15:53 UTC, rrrene requested changes
Almost there. This will be a nice addition to Credo's list of standard checks :+1:

2020-12-12 15:53 UTC, rrrene commented on lib/credo/check/warning/spec_with_struct.ex
> +       when atom in ~w(:: when)a do
What I meant was, that we should be looking for a module attribute here:

```elixir
  defp traverse({:@, _, [{:spec, meta, args}]}, issues, issue_meta) do
```

2020-12-12 15:53 UTC, rrrene commented on lib/credo/check/warning/spec_with_struct.ex
> +    {ast, Enum.join(modules, ".")}
Missed this in the first pass: This should use `Credo.Code.Name.full/1`.

2020-12-12 15:53 UTC, rrrene commented on test/credo/check/warning/spec_with_struct_test.exs
> +  @a_struct_module """
> I wanted to test that I could catch multiple issues for different structs

That is the right goal. Unfortunately, the check does not catch multiple Structs if they are part of the same `@spec`.

2020-12-12 15:53 UTC, rrrene commented on test/credo/check/warning/spec_with_struct_test.exs
> +        @spec g(a_struct :: %AStruct{}) :: any
The test suite is missing a case, where we test multiple structs in a single `@spec`:

```elixir
        @spec g(a_struct :: %AStruct{}, my_struct :: %MyApp.MyStruct{}) :: any
```

2020-12-12 17:10 UTC, andersonmcook commented on test/credo/check/warning/spec_with_struct_test.exs
> +  @a_struct_module """
Thanks! I updated the code and test to cover this case.

2020-12-12 17:11 UTC, andersonmcook commented on test/credo/check/warning/spec_with_struct_test.exs
> +        @spec g(a_struct :: %AStruct{}) :: any
Thanks!  I added a test on line 132 to cover this.

2020-12-13 10:32 UTC, rrrene commented
LGTM! :+1: Thx!

2020-12-13 10:32 UTC, merged