Add forbiddenForbiddenModule
rrrene/credo pull request #855
Opened 2021-02-27 00:48 UTC by spencerdcarlson

# Proposal
Add `Credo.Check.Warning.ForbiddenModule` that can be configured to black list a list of modules.

### Example .credo.exs usage
```elixir
...
checks: [
  {Credo.Check.ForbiddenModule, [modules: [Ecto.Adapters.SQL]]}
]
```

### mix credo explain Credo.Check.ForbiddenModule
<img width="733" alt="Screen Shot 2021-02-26 at 5 45 11 PM" src="https://user-images.githubusercontent.com/1206303/109369682-847b6080-785a-11eb-87a5-87c11e2b940a.png">

### Example Violation
<img width="625" alt="Screen Shot 2021-02-26 at 5 47 47 PM" src="https://user-images.githubusercontent.com/1206303/109369742-ca382900-785a-11eb-9dd5-f3e0fa3f50d0.png">

2021-02-27 07:47 UTC, NickNeck commented
Hello @spencerdcarlson 

that looks great and interesting.

One problem could be that the list of modules depends on the project. I understand Credo more as a checker for general code styles.

If you want to have such boundaries in your project, you could check out https://github.com/sasa1977/boundary

Maybe you can add predefined lists of modules for well-known libs. Like:
`modules: [:ecto, :phoenix]`.

Another feature could be to add all hidden modules to the list of forbidden modules: 
```elixir
:code.all_loaded() |> Enum.filter(fn {m,_} -> match?({_,_,_,_,:hidden,_,_}, Code.fetch_docs(m)) end)
```
In this case, you must also check the root module.
```
ok   : MyApp.Worker using MyApp.HiddenUtil 
error: MyAppWeb.Foo using MyApp.HiddenUtil
```

2021-03-04 19:10 UTC, rrrene requested changes
@spencerdcarlson This seems like a worthwhile endeavour. 👍 

Could please go into more detail re: "Which are the scenarios where you needed/used this?"

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +
Please remove the `@moduledoc` as checks do not have them (they are generated).

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +
Please re-order the `alias` below the `use` statements (as seen in all other checks in Credo).

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +    base_priority: :high,
Why would this check be of high priority to the regular user?

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +    category: :warning,
Why is this a `warning`?

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +      These modules are are forbidden.
Please put a bit more effort into the explanation of the check's existence. Why would anyone want to deny usage of a certain list of modules?

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +      params: [modules: "This check warns about modules that can not be used."]
This is a description of the parameter, not the check. Please describe what the parameter does.

Also: Not a native speaker, but shouldn't this be "must" instead of "can"?

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +      |> List.wrap()
Please use `Params.get/3` here instead.

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +    # Catches import and alias statements for a forbidden module
Please don't write comments literally describing what happens in the next line.

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +    Enum.all?(module, &is_atom/1) && Enum.member?(forbidden_modules, Module.concat(module))
Why do we need the `Enum.all?(module, &is_atom/1)`?

2021-03-04 19:10 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +  defp mod_string(module), do: ~r/Elixir\./ |> Regex.replace(to_string(module), "")
Please use `Credo.Code.Module.name/1`.

2021-03-04 19:10 UTC, rrrene commented on test/credo/check/warning/forbidden_module_test.exs
> +  test "it should report on aliases" do
Your missing the most basic case here:

```elixir
    defmodule CredoSampleModule do
      def some_function do
        CredoSampleModule.ForbiddenModule.another_function()
      end
    end
```

2021-03-05 00:17 UTC, spencerdcarlson commented on test/credo/check/warning/forbidden_module_test.exs
> +  test "it should report on aliases" do
That test case is here on [L63-L72](https://github.com/rrrene/credo/pull/855/files#diff-2dedc3870ab83967d2ae9c6aa3a4d19f542f72d90728b7e56ff9a753060180e2R63-R72). I'll move it up to be first in the list.

2021-03-05 00:22 UTC, spencerdcarlson commented on lib/credo/check/warning/forbidden_module.ex
> +    Enum.all?(module, &is_atom/1) && Enum.member?(forbidden_modules, Module.concat(module))
I removed this, it was left over from a prior approach to catch inline usage.

2021-03-05 00:24 UTC, spencerdcarlson commented on lib/credo/check/warning/forbidden_module.ex
> +    category: :warning,
When I have used this Check on projects, it is usually critical that a given module is forbidden because it could cause issues. I have no preference here, what would you recommend?

2021-03-05 00:24 UTC, spencerdcarlson commented on lib/credo/check/warning/forbidden_module.ex
> +    base_priority: :high,
When I have used this Check on projects, it is usually critical that a given module is forbidden because it could cause issues. I have no preference here, what would you recommend?

2021-03-05 00:54 UTC, spencerdcarlson commented on lib/credo/check/warning/forbidden_module.ex
> +      These modules are are forbidden.
Updaed.

2021-03-05 01:02 UTC, spencerdcarlson commented
> @spencerdcarlson This seems like a worthwhile endeavour. 👍
> 
> Could please go into more detail re: "Which are the scenarios where you needed/used this?"

Hopefully my updated explanation makes it more clear:

>Some modules that are included by a package may be hazardous
      if used by your application. Use this check to allow these modules in
      your dependencies but forbid them to be used in your application.

>Examples:
      The `:ecto_sql` package includes the `Ecto.Adapters.SQL` module,
      but direct usage of the `Ecto.Adapters.SQL.query/4` function, and related functions, may
      cause issues when using Ecto's dynamic repositories.


Because internally [Ecto.Adapters.SQL.query/4](https://github.com/elixir-ecto/ecto_sql/blob/v3.5.4/lib/ecto/adapters/sql.ex#L420-L426) does not call [Repo.get_dynamic_repo/0](https://hexdocs.pm/ecto/Ecto.Repo.html#c:get_dynamic_repo/0) before executing the query, usage the adapter's functions could be hazardous. Instead we need to require developers to use [Ecto.Repo.query/3](https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/sql.ex#L512-L545) instead.

2021-05-17 16:55 UTC, rrrene reviewed
After a longer-than-anticipated absence, this check proposal has really grown on me :+1:

One thing I wished this had is the ability to provide a custom message for a forbidden module:

```elixir
# .credo.exs

# ...
    {Credo.Check.Warning.ForbiddenModule, modules: [{Ecto.Adapters.SQL, "jesus, team, please stop using this!!!11"}]},
# ...
```

WDYT?

2021-05-17 16:55 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +    base_priority: :high,
I'd just leave it for the user to decide :+1:

2021-05-17 16:55 UTC, rrrene commented on lib/credo/check/warning/forbidden_module.ex
> +    category: :warning,
You're right. Thinking about it, `warning` is probably the most sensible choice here :+1:

2021-08-03 07:19 UTC, rrrene commented
@spencerdcarlson Any news on this? If you could add the ability to provide a custom message for a forbidden module, we'll make this part of Credo v1.6 :+1:

2021-08-08 07:41 UTC, spencerdcarlson commented
> @spencerdcarlson Any news on this? If you could add the ability to provide a custom message for a forbidden module, we'll make this part of Credo v1.6 👍

Thanks, I added the custom message feature. Let me know if there is anything you want me to change.

2021-08-08 08:27 UTC, rrrene approved these changes

2021-08-08 08:27 UTC, merged

2021-08-08 08:28 UTC, rrrene commented
@spencerdcarlson Thx! 🎉  :+1: