Add new check for one-arity functions in pipes
rrrene/credo pull request #905
Opened 2021-11-01 19:05 UTC by NickNeck

Some style guides propose:
> Use parentheses for one-arity functions when using the pipe operator (|>)
> ```elixir
> # not preferred
> some_string |> String.downcase |> String.trim
> 
> # preferred
> some_string |> String.downcase() |> String.trim()
> ```
This PR provides a check for that.

2021-12-23 16:10 UTC, rands0n commented on lib/credo/check/readability/one_arity_function_in_pipe.ex
> +      ```
Did you open this ``` in someplace before?

2022-01-02 09:50 UTC, rrrene requested changes
This seems good, just a few minor nitpicks :+1:

2022-01-02 09:50 UTC, rrrene commented on .credo.exs
> +          {Credo.Check.Readability.OneArityFunctionInPipe, []},
We should not add checks as default, esp. when it's rules that "some style guides" propose :+1:

2022-01-02 09:50 UTC, rrrene commented on lib/credo/check/readability/one_arity_function_in_pipe.ex
> +  defp issue({:|>, _meta, [_left, {name, meta, nil}]}, issue_meta) when is_atom(name) do
This should be matched in `traverse/3` not in the issue-creating function (see every other check).

2022-12-30 13:35 UTC, merged

2022-12-31 15:07 UTC, rrrene commented
This is part of Credo [v1.7.0-rc.1](https://hex.pm/packages/credo/1.7.0-rc.1) :+1: