add new check for pipe per line
rrrene/credo pull request #927
Opened 2021-12-23 16:14 UTC by rands0n

Some style guide proposes:

```elixir
# not preferred

1 |> Integer.to_string() |> String.to_integer()

# preferred

1
|> Integer.to_string()
|> String.to_integer()
```

This PR provides a check for that.

2022-01-02 09:52 UTC, rrrene requested changes
This seems off to a great start. See comments below :+1:

2022-01-04 12:46 UTC, rands0n commented on lib/credo/check/readability/pipe_per_line.ex
> +    base_priority: :high,
Which priority do you recommend?

2022-01-04 15:38 UTC, bamorim commented on lib/credo/check/readability/pipe_per_line.ex
> +  defp filter_tokens({_, [_ | _]}), do: true
```suggestion
  defp filter_tokens({_, [_ | _]}), do: true
  defp filter_tokens(_), do: false
```

2022-01-04 21:43 UTC, rrrene commented on lib/credo/check/readability/pipe_per_line.ex
> +    base_priority: :high,
I was just asking for your reasons. If you have none, just remove `:base_priority` and the check gets the "standard" priority between high and low 👍

2022-01-05 17:09 UTC, rands0n commented on lib/credo/check/readability/pipe_per_line.ex
> +    base_priority: :high,
Removed 🥇 

Thanks

2022-02-15 18:58 UTC, rands0n commented
Any news?

2022-03-27 08:34 UTC, rrrene commented
This looks good. 

The last thing I am wondering is if we covered all edge cases in the tests though. 

Are there things we could be missing? Like "exotic" combinations of single line and multi line pipes?

```elixir
String.to_integer(1 |> Integer.to_string()) 
|> Integer.to_string()
```

2022-03-28 14:57 UTC, bamorim commented
@rrrene that is a good point. The current approach just count pipes per line, so something like

```elixir
value
|> do_something(:a |> to_string())
|> do_something_else()
```

Would fail. If we want this to be accepted, we would need to change. If we don't mind that much, we could suggest that this is changed either to an extracted variable or to something like

```elixir
value
|> do_something(
  :a
  |> to_string()
)
|> do_seomthing_else()
```

2022-03-29 08:52 UTC, bamorim commented
The implementation to support that case would require us parsing the AST and counting `|>` per line per tree depth, which is harder to implement and I'm not sure worth it.

2022-05-17 15:03 UTC, rands0n commented
@rrrene ping

2022-12-30 14:01 UTC, merged

2022-12-31 15:07 UTC, rrrene commented
This is part of Credo [v1.7.0-rc.1](https://hex.pm/packages/credo/1.7.0-rc.1) :+1: