Create CondCatchallTrue readability check
rrrene/credo pull request #935
Opened 2022-01-05 22:21 UTC by Stratus3D

This PR adds a check named `Credo.Check.Readability.CondCatchallTrue` that checks for `cond`s that end in a catchall clause that use a literal value other than `true`. I created this check to catch violations of the rule about catchall `cond` clauses specified in the Christopher Adam's style guide (https://github.com/christopheradams/elixir_style_guide#expressions). See the tests for examples.

Context:

* https://github.com/christopheradams/elixir_style_guide/issues/143#issuecomment-394191496

2022-01-05 22:31 UTC, Stratus3D commented on lib/credo/check/readability/cond_catchall_true.ex
> +defmodule Credo.Check.Readability.CondCatchallTrue do
Open to suggestions on what to name this check. I had a hard time picking a name and I'm not sure this name is best.

2022-01-05 22:32 UTC, Stratus3D commented on lib/credo/check/readability/cond_catchall_true.ex
> +  defp catchall_other_than_true?(_), do: false
Returns true of the clause condition is a catchall that isn't the literal value `true`.

2022-01-09 21:44 UTC, rrrene commented
Great :+1: 

Since the Elixir website & documentation call this the "final condition", we should name this `CondFinalCondition`.

Also, I do think the `true` should be a config parameter for this check. I can't think of a reason why we would exclude people using `:else` from the ability to check for it (although `true` should be the default to match the linked styleguide). :+1:

2022-01-10 15:06 UTC, Stratus3D commented
> Great 👍
> 
> Since the Elixir website & documentation call this the "final condition", we should name this `CondFinalCondition`.
> 
> Also, I do think the `true` should be a config parameter for this check. I can't think of a reason why we would exclude people using `:else` from the ability to check for it (although `true` should be the default to match the linked styleguide). 👍

PR updated!

2022-01-13 22:01 UTC, rkledesma commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should report conds that with a last condition that is binary literal" do
suggestion```
test "it should report conds with a last condition that is binary literal" do
```

2022-01-13 22:03 UTC, rkledesma commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should report conds that with a last condition that is integer literal" do
```suggestion
  test "it should report conds with a last condition that is integer literal" do
```

2022-01-13 22:05 UTC, rkledesma commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should report conds that with a last condition that is list literal" do
```suggestion
  test "it should report conds with a last condition that is a list literal" do
```

2022-01-13 22:06 UTC, rkledesma commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should report conds that with a last condition that is tuple literal" do
```suggestion
  test "it should report conds with a last condition that is a tuple literal" do
```

2022-01-13 22:06 UTC, rkledesma commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should report conds that with a last condition that is map literal" do
```suggestion
  test "it should report conds with a last condition that is a map literal" do
```

2022-01-13 22:08 UTC, rkledesma commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should NOT report conds that with a last condition that match config" do
```suggestion
  test "it should NOT report conds with a last condition that match the config" do
```

2022-01-14 14:11 UTC, Stratus3D commented
@rrrene this is ready for review again!

2022-01-21 13:47 UTC, Stratus3D commented
@rrrene any chance you can take a look at this PR again?

2022-01-21 14:50 UTC, rrrene requested changes
Apologies, I'm having the first cold in 2.5 years and am no longer used to that *%&/!.

Did you use a formatter on the code?

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +      |> catchall_other_than_value?(final_condition_value) do
Please extract this condition into a variable.

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +        final_condition_value: "Set the expected value for the final condition"
Please rename this to `value`, since we don't repeat the check's name in param names for any other check.

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +      "Cond statements that end with an \"always true\" condition should use `true` instead of some other literal.",
The message should not specify `true` as the value if another value has been set.

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +  defp catchall_other_than_value?(_clause, _value), do: false
If the clauses "above" this one are "catch alls" for all cases, what are examples where we need this clause?

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +  defp catchall_other_than_value?({:->, _meta, [[value], _args]}, value), do: false
Please rename this function to something that gives a hint at what it does.

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +  defp catchall_other_than_value?({:->, _meta, ['{', _args]}, _value), do: true
Why does this always return `true`, no matter what I specified in the config?

2022-01-21 14:50 UTC, rrrene commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should NOT report conds with a last condition of true" do
Could you please group the tests which are not raising issues at the top of the test file? For examples, look at any standard check.

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +  use Credo.Check,
Please add

```
    tags: [:controversial],
```

here as this will not be a standard check since it is implementing a community style guide which not everybody agrees upon.

2022-01-21 14:50 UTC, rrrene commented on test/credo/check/readability/cond_final_condition_test.exs
> +  alias Credo.Check.Readability.CondFinalCondition
Please use a module attribute for the check instead of an alias (see any standard check's test file for an example).

2022-01-21 14:50 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +      """,
If this is a Readability check, then this needs the readability disclaimer at the end of the explanation that all other standard readability checks have.

2022-01-21 14:58 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +      {ast, issues ++ [issue_for(issue_meta, meta[:line], :cond)]}
Why is the `trigger` for the issue always "cond"? The trigger is the word in the code that "triggers" the issue and that should be the "wrong" final condition, e.g. using `:else` when using `true` is expected.

2022-01-21 16:15 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +  defp catchall_other_than_value?(_clause, _value), do: false
This is for a non catch-all clause. A contrived example:

```
 cond do
   n > 5 ->
     "greater than 5"
   n >= 0 ->
     "positive"
   n < 0 ->
     "negative"
end
```

The last clause is not a catchall and is not composed of a single literal. I will add a comment for this final clause. Let me know if you think I should rename this function.

2022-01-21 16:20 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +  defp catchall_other_than_value?({:->, _meta, ['{', _args]}, _value), do: true
This function returns false when the `value` variable bound by the match of the first argument (`{:->, _meta, [[value], _args]}`) matches the second argument `value`. The second argument passed to this function is value specified in the config.

2022-01-21 17:25 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +      |> catchall_other_than_value?(final_condition_value) do
PR updated.

2022-01-21 17:26 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +        final_condition_value: "Set the expected value for the final condition"
PR updated.

2022-01-21 17:26 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +      "Cond statements that end with an \"always true\" condition should use `true` instead of some other literal.",
PR updated.

2022-01-21 17:27 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +  defp catchall_other_than_value?({:->, _meta, [[value], _args]}, value), do: false
PR updated. Let me know if the new name is acceptable.

2022-01-21 17:27 UTC, Stratus3D commented on test/credo/check/readability/cond_final_condition_test.exs
> +  test "it should NOT report conds with a last condition of true" do
PR updated.

2022-01-21 17:27 UTC, Stratus3D commented on test/credo/check/readability/cond_final_condition_test.exs
> +  alias Credo.Check.Readability.CondFinalCondition
PR updated.

2022-01-21 17:27 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +      """,
PR updated.

2022-01-21 17:29 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +      {ast, issues ++ [issue_for(issue_meta, meta[:line], :cond)]}
PR updated. The trigger is now the literal catchall value, or in the case of maps, tuples, and integers, the atom `:map`, `:tuple` or `:integer`. Let me know if this is acceptable.

2022-01-21 17:29 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +  use Credo.Check,
PR updated.

2022-01-21 17:37 UTC, Stratus3D commented
> Apologies, I'm having the first cold in 2.5 years and am no longer used to that *%&/!.
> 
> Did you use a formatter on the code?

Sorry to hear you have been sick. Thanks for the review and thank you for all your work on credo!

I forgot to run the formatter when I opened the PR. I ran it and pushed the reformatted code. Everything is ready to review again.

2022-01-22 14:53 UTC, rrrene commented on lib/credo/check/readability/cond_final_condition.ex
> +      {ast, issues ++ [issue_for(issue_meta, meta[:line], :cond)]}
As I mentioned before

> The trigger is the word in the code that "triggers" the issue

which means the actual string that should get squiggly lines in your editor.

2022-01-24 21:02 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +      {ast, issues ++ [issue_for(issue_meta, meta[:line], :cond)]}
I'm sorry about that. I don't know how to do that but I'll see if I can figure it out. Are there any other checks that I could refer to that do this?

2022-01-25 16:36 UTC, Stratus3D commented on lib/credo/check/readability/cond_final_condition.ex
> +      {ast, issues ++ [issue_for(issue_meta, meta[:line], :cond)]}
PR updated. I have added assertions to the tests for this check to verify that the clause expression that triggers issue is what is set for the issue's `trigger` parameter.

2022-01-25 16:40 UTC, Stratus3D commented
I have updated the PR again based on your reply to one of my comments about the issue trigger value. The trigger is now set to the string of code that triggered the issue. The PR is ready to review again.

2022-02-03 19:00 UTC, Stratus3D commented
Any chance this can get merged soon?

2022-02-05 14:13 UTC, rrrene commented
> I have added assertions to the tests for this check to verify that the clause expression that triggers issue is what is set for the issue's trigger parameter.

This is good in principle, but it does not work if I modify your tests to something that might very well happen in real life (a dangling space somewhere):

```
*..................................................................................................................................................................................................................................................................................................................................

  1) test it should report conds with a last condition that is a list literal (Credo.Check.Readability.CondFinalConditionTest)
     test/credo/check/readability/cond_final_condition_test.exs:141
     Assertion with == failed
     code:  assert "[:else ]" == trigger
     left:  "[:else ]"
     right: "[:else]"
     stacktrace:
       (credo 1.6.2) lib/credo/test/assertions.ex:30: Credo.Test.Assertions.assert_issue/2
       test/credo/check/readability/cond_final_condition_test.exs:160: (test)

.

  2) test it should report conds with a last condition that is a tuple literal (Credo.Check.Readability.CondFinalConditionTest)
     test/credo/check/readability/cond_final_condition_test.exs:165
     Assertion with == failed
     code:  assert "{ :else }" == trigger
     left:  "{ :else }"
     right: "{:else}"
     stacktrace:
       (credo 1.6.2) lib/credo/test/assertions.ex:30: Credo.Test.Assertions.assert_issue/2
       test/credo/check/readability/cond_final_condition_test.exs:184: (test)

.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

2022-02-14 15:02 UTC, Stratus3D commented
@rrrene I copied what was done in the existing checks. I used `Macro.to_string(ast)` to convert the AST back into the original expression and passed that into the issue as the trigger value.

Can you provide a suggestion on how to improve this? Happy to change things but not sure how.

2022-03-17 13:17 UTC, Stratus3D commented
@rrrene, I'd like to get this merged, can you show me how to address this in credo? I'm not sure I can get the cond clause with whitespace in credo.

> This is good in principle, but it does not work if I modify your tests to something that might very well happen in real life (a dangling space somewhere):

> Can you provide a suggestion on how to improve this? Happy to change things but not sure how.

Thanks!

2022-11-30 19:40 UTC, Stratus3D commented
Re-opening this PR as I closed it in error. @rrrene happy to make any changes to get this merged!

2022-12-12 14:10 UTC, Stratus3D commented
@rrrene you've merged several of my checks but not this one. If you can provide any info as to why this hasn't been accepted yet I will be happy to make any necessary changes (or close it permanently if that is needed).

2022-12-30 13:43 UTC, rrrene commented
> If you can provide any info as to why this hasn't been accepted yet

Hi, sorry for being a slow responder. This check won't get merged as long as it assumes that people write code the same way that `Macro.to_string/1` translates ASTs. This is just an unrealistic expectation.

I do not have an "obvious" solution for your specific problem here (a.k.a. I'm not trolling you).

2023-02-03 21:38 UTC, rrrene commented
I am closing this for age/inactivity. 

If you find a way to make the final changes, please feel free to re-open this issue at your discretion.

2023-02-03 21:38 UTC, closed without merging

2023-03-13 14:57 UTC, Stratus3D commented
Hi @rrrene , sorry for the late reply here.

> Hi, sorry for being a slow responder. This check won't get merged as long as it assumes that people write code the same way that Macro.to_string/1 translates ASTs. This is just an unrealistic expectation.

Are you referring to this line? https://github.com/rrrene/credo/pull/935/files#diff-cbac4e2c2b102d2eba670658d03634fb4b21022007e98f39f5b7bccd674e52daR57 The `Credo.Check.Warning.ExpensiveEmptyEnumCheck` already uses `Macro.to_string/1` to translate AST into code for the error (see https://github.com/rrrene/credo/blob/master/lib/credo/check/warning/expensive_empty_enum_check.ex#L66).

Is there a reason this is problematic? I understand the code may not be formatted exactly as the user typed it in, but I'm not sure this will be a big problem as we do output the line number as well, so the user should be able to locate the problem without issue. Remember, this AST in this case is only ever going to be a catchall clause **literal** value. So for example, `:else`, `%{random: value}`, `[]`, `[1,2,3]`, etc... it'll never be an anything other than a literal. While it's true the user may have formatted the literal differently, it I don't think it'll be a big problem in practice. The only alternative to I see to this would be to remove the `trigger` from reported issues entirely, which probably is not desired.