feat: Add Allow option Credo.Check.Readability.ModuleNames configurable
rrrene/credo pull request #996
Opened 2022-09-02 10:34 UTC by BobrImperator

- Adds :allow param
  - :allow is a list of strings or regexes
- Adds tests for the functionality

Given
  allow: [Sample_Module]

Credo.Sample_Module will pass ✅ 
Credo.Another_Module.Sample_Module will fail ❌

2022-09-02 11:09 UTC, tomekowal commented on lib/credo/check/readability/module_names.ex
> +        is_allowed_segment? or is_pascal_case?
Not sure if it has a significant impact, but the code performs this additional work even if the name is pascal case.
If the `is_allowed_segment?` is transformed into a function, you could write
`Name.pascal_case? or is_pascal_case?(segment, allowed_patterns)`
and that would short circuit and not run the code that does Regex or any other expensive stuff.

2022-09-02 11:24 UTC, BobrImperator commented on lib/credo/check/readability/module_names.ex
> +        is_allowed_segment? or is_pascal_case?
Good point 👍 
Applied the feedback

2022-09-02 11:25 UTC, tomekowal approved these changes

2022-09-02 13:32 UTC, rrrene commented
Why would you open a PR for something and then write a proposal for it 40 minutes later?

2022-09-02 13:43 UTC, BobrImperator commented
@rrrene I thought that's the process and that It'd also be nice for discoverability

2022-09-02 14:15 UTC, rrrene requested changes
I'm not sure if you are serious ... anyway, please find my review attached.

2022-09-02 14:15 UTC, rrrene commented on lib/credo/check/readability/module_names.ex
> +      allow: []
This should be called `:ignore` since the given module names should be exempt from the rule and thus ignored by the check (see several other checks providing an `:ignore` parameter).

2022-09-02 14:15 UTC, rrrene commented on lib/credo/check/readability/module_names.ex
> +          "List of allowed name segment patterns e.g. `[~r/Sample_Module/, \"Sample_Module\"]`"
I absolutely dislike this idea of "segments". Why would I want to define patterns for segments instead of patterns for module names to ignore?

2022-09-02 14:15 UTC, rrrene commented on lib/credo/check/readability/module_names.ex
> +         allowed_segment?(allowed_patterns, segment) or Name.pascal_case?(segment)
You have not applied @tomekowal's feedback here to put `Name.pascal_case?/1` first.

2022-09-02 14:15 UTC, rrrene commented on lib/credo/check/readability/module_names.ex
> +        String.equivalent?(segment, to_string(module_name))
Could please provide cases where we would need `String.equivalent/2` for the comparison?

2022-09-02 14:15 UTC, rrrene commented on test/credo/check/readability/module_names_test.exs
> +    |> run_check(@described_check, allow: ["Another_Module", "Sample_Module"])
This is a good example for why I think this "segment approach" is not good.

I want to ignore a module and need to put two patterns to do that.

2022-09-02 14:15 UTC, rrrene commented on test/credo/check/readability/module_names_test.exs
> +    |> run_check(@described_check, allow: ["Sample_Module"])
You have no test that covers your "core module".

```
"""
defmodule Sample_Module do
end
"""
|> to_source_file
|> run_check(@described_check, allow: ["Sample_Module"])
```

2022-09-02 14:15 UTC, rrrene commented on lib/credo/check/readability/module_names.ex
> +    segments =
Again, why would you choose checking "segments" over just listing modules and patterns that should be ignored by the check?

2022-09-02 14:27 UTC, BobrImperator commented on lib/credo/check/readability/module_names.ex
> +        String.equivalent?(segment, to_string(module_name))
So the rule could either take a regex `~r/Some_Module/` or simply a string `"Some_Module"`.
I guess if you'd prefer to abandon checking against segments then it'd be not needed.

2022-09-02 14:31 UTC, BobrImperator commented on test/credo/check/readability/module_names_test.exs
> +    |> run_check(@described_check, allow: ["Another_Module", "Sample_Module"])
That's incorrect. It doesn't require to provide a path in chunks.

In this example it allows 2 modules.
If it were as you're saying, then the rule would require to type `allow: ["Credo", "Another_Module", "Sample_Module"]`

2022-09-02 15:28 UTC, tomekowal commented on test/credo/check/readability/module_names_test.exs
> +    |> run_check(@described_check, allow: ["Another_Module", "Sample_Module"])
I feel there is a slight misunderstanding between you two about the goal of that PR.

@BobrImperator use case is having version number in the module name. E.g. for v1.1 some modules would have the version in the name `V1_1`, e.g. `MyApp.V1_1.SomeController`, `MyApp.V1_1.SomeControllerTest`, `MyApp.V1_1.SomeOtherController` and so on... So far, we've specified `# credo:disable-for-this-file Credo.Check.Readability.ModuleNames` for each of those. That is why he wants to specify a "segment" that is considered valid. However, he would still like to catch `My_App.V1_1.Some_Controller` because that would be wrong.

But in Credo, no rules were working on "segments" so far. Segments were just an implementation detail of this particular function. If working on segments is confusing for @rrrene, it would also be confusing to other users.

I think working on module names might be less confusing. If any module "segment" matches the pattern, it is ignored. The downside is that if we ignore `V1_1` then `My_App.V1_1.Some_Controller` will be valid (it will be less strict than the version of @BobrImperator because it will ignore the entire module name). However, it might be easier to grasp.

2022-09-02 16:54 UTC, rrrene commented on test/credo/check/readability/module_names_test.exs
> +    |> run_check(@described_check, allow: ["Another_Module", "Sample_Module"])
@BobrImperator Tomasz already summarized the main point here: The fact that the original implementation worked on the individual parts of the fullname is just an implementation detail.

For a good user experience, we should think from a user's perspective and I would argue that most users think "I want to ignore `MyProject.Foo_Bar`.

@tomekowal While it is less strict for your example, it is also more powerful. Using Regex, you can easily allow for your exact scenario (`~r/^[^_]+\.V\d+_\d+\.[^_]+$/`). :+1:

2022-09-02 16:54 UTC, rrrene commented on lib/credo/check/readability/module_names.ex
> +        String.match?(module_name, pattern)
I probably wasn't clear on this one: I liked your idea of supporting binaries, atoms and regexes :+1: 

```
ignore: ["Credo.Code.My_Module", Credo.Code.My_Module, ~r/My_Module/]
```

This would be great for different scenarios of different complexity I outlined in the other comment.

I just wasn't convinced by the usage of `String.equivalent/2` instead of `==` (as equivalent seems to be for other use cases).

2022-12-30 22:38 UTC, merged

2022-12-31 15:05 UTC, rrrene commented
This is part of Credo [v1.7.0-rc.1](https://hex.pm/packages/credo/1.7.0-rc.1) :+1: