feat: warn on dbg calls
rrrene/credo pull request #997
Opened 2022-09-02 14:07 UTC by ding-an-sich

Implements a warning for calls to the dbg/0 or dbg/2 Kernel fns.

I used the IO.inspect check as a reference.

2022-09-02 17:30 UTC, rrrene requested changes
Thanks for putting this together!

A few minor nitpicks below:

2022-09-02 17:30 UTC, rrrene commented on test/credo/check/warning/dbg_test.exs
> +    end
I think we are missing a couple of important examples for "expected code" that should not yield an issue:

```suggestion
    defmodule CredoSampleModule do
      @dbg :should_not_raise_an_issue
      
      def dbg(my_param) do
        # ...
      end
      
      def some_function(parameter1, parameter2) do
        dbg(parameter1)
      end
      
      def some_other_function(parameter1, parameter2) do
        dbg = parameter1 + parameter2
      end
    end
```

2022-09-02 17:30 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +      or the dbg/2 Kernel fn.
Nitpicking for good measure: Let's change this to

```suggestion
      Calls to dbg/2 and dbg/3 should mostly be used during debugging sessions.

      This check warns about those calls, because they probably have been committed
      in error.
```

2022-09-02 17:30 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +    base_priority: :high,
We could think about deactivating this check for older versions of Elixir:

```suggestion
    base_priority: :high,
    elixir_version: ">= 1.14.0-dev",
```

2022-09-02 21:31 UTC, ding-an-sich commented on test/credo/check/warning/dbg_test.exs
> +    end
Those were a lot trickier so I had to rewrite the check from scratch.

2022-09-02 21:57 UTC, ding-an-sich commented
I decided to not check for the use of Macro.dbg/3 because that function could be used as a fallback when building custom backends for dbg().

2022-09-03 13:30 UTC, ding-an-sich commented
I have streamlined the way we check if a given :dbg call should be a warning or not. If the user attempts to override the auto-imported dbg fns dbg/0, dbg/1, dbg/2 he'll get a compile error, so we shouldn't worry about those.

2022-09-03 17:41 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +    is_dbg? = Enum.count_until(args, @dbg_max_arity + 1) < @dbg_max_arity + 1
This is unnecessary, you can just match for 

```elixir
{:dbg, meta, [_single_param]} = ast,
```

and 

```elixir
{:dbg, meta, [_first_param, _second_param]} = ast,
```

to match the two cases where you want to raise an issue. Matching is always better than counting :+1:

2022-09-03 17:41 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +  defp traverse({:=, _meta, children} = ast, acc) do
This does only catch matching a variable, but not using it, e.g.

```elixir
x = dbg + something
```

is not matched as well as


```elixir
some_fun(dbg)
```

You just have to add a case where you match on variable usage to catch all those cases and not raise an issue:

```elixir
  defp traverse(
         {:dbg, _meta, nil} = ast,
         acc
       ) do
    {ast, acc}
  end
```

Next, you can lose the `acc` construct for good 👍

2022-09-03 17:41 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +         {:dbg, meta, nil} = ast,
Regarding my earlier comment: Why do we need `acc` if you already match on the `nil` case here?

2022-09-03 18:24 UTC, ding-an-sich commented on lib/credo/check/warning/dbg.ex
> +    is_dbg? = Enum.count_until(args, @dbg_max_arity + 1) < @dbg_max_arity + 1
True! Will refactor!

2022-09-03 18:42 UTC, ding-an-sich commented on lib/credo/check/warning/dbg.ex
> +         {:dbg, meta, nil} = ast,
We have to differentiate between `dbg = something` and `dbg()` (i.e. the use of dbg/0).

2022-09-03 18:44 UTC, ding-an-sich commented on lib/credo/check/warning/dbg.ex
> +         {:dbg, meta, nil} = ast,
Oooo, I did not realize that calling dbg() actually builds a node with an empty child list `[]` and defining/using a variable builds a node with `nil` as child. That significantly simplies things.

2022-09-03 18:51 UTC, ding-an-sich commented on lib/credo/check/warning/dbg.ex
> +         {:dbg, meta, nil} = ast,
Should be a lot simpler now that all matches are unambiguous.

2022-09-03 18:54 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +         {:dbg, meta, nil} = ast,
Great. I also think the code is much more readable now :+1:

2022-09-06 08:27 UTC, wingyplus commented on lib/credo/check/warning/dbg.ex
> +         {{:., _, [{:__aliases__, _, [:Kernel]}, :dbg]}, meta, _args} = ast,
We should add 1 case for `Elixir.Kernel.dbg`

Ref: https://github.com/rrrene/credo/pull/998/files#diff-5c99577ee3ac0438232258234dece6b69f1649a7f430290e09fbeaf5dec67b0aR34-R40

2022-09-08 18:50 UTC, rrrene commented on lib/credo/check/warning/dbg.ex
> +         {{:., _, [{:__aliases__, _, [:Kernel]}, :dbg]}, meta, _args} = ast,
@wingyplus Out of curiosity: Is this for cases were I explicitly spell `Elixir.Kernel.dbg(arg)` in my code?

2022-09-09 00:12 UTC, wingyplus commented on lib/credo/check/warning/dbg.ex
> +         {{:., _, [{:__aliases__, _, [:Kernel]}, :dbg]}, meta, _args} = ast,
@rrrene yes. But I think it’s rare case to calling a function like this in elixir.

2022-12-06 10:50 UTC, ding-an-sich commented
@rrrene, any chance to get this rolling again? Not sure how to tackle the red CI checks.

2022-12-09 08:05 UTC, rrrene reviewed
Absolutely. We just have to add an ID for the upcoming SARIF support (#1011)

2022-12-09 17:05 UTC, merged

2022-12-31 15:05 UTC, rrrene commented
This is part of Credo [v1.7.0-rc.1](https://hex.pm/packages/credo/1.7.0-rc.1) :+1: